// Code generated by "stringer -type=Priority,VMState"; DO NOT EDIT.

package driver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Obsolete-1]
	_ = x[Unhealthy-2]
	_ = x[Experimental-3]
	_ = x[Discouraged-4]
	_ = x[Deprecated-5]
	_ = x[Fallback-6]
	_ = x[Default-7]
	_ = x[Preferred-8]
	_ = x[HighlyPreferred-9]
}

const _Priority_name = "UnknownObsoleteUnhealthyExperimentalDiscouragedDeprecatedFallbackDefaultPreferredHighlyPreferred"

var _Priority_index = [...]uint8{0, 7, 15, 24, 36, 47, 57, 65, 72, 81, 96}

func (i Priority) String() string {
	if i < 0 || i >= Priority(len(_Priority_index)-1) {
		return "Priority(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Priority_name[_Priority_index[i]:_Priority_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Starting-1]
	_ = x[Running-2]
	_ = x[Paused-3]
	_ = x[Stopping-4]
	_ = x[Stopped-5]
	_ = x[Error-6]
}

const _VMState_name = "NoneStartingRunningPausedStoppingStoppedError"

var _VMState_index = [...]uint8{0, 4, 12, 19, 25, 33, 40, 45}

func (i VMState) String() string {
	if i < 0 || i >= VMState(len(_VMState_index)-1) {
		return "VMState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VMState_name[_VMState_index[i]:_VMState_index[i+1]]
}
